// Generates an OrcaSlicer-style g-code fixture for tests.
// Multiple layers, 4 perimeters (outer + 3 inner), Z-shift brick lines inside
// inner walls so the nesting detection is exercised, sparse infill, wipes,
// retractions, and a final ;TYPE:Custom end-of-print.
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
mkdirSync(join(here, 'golden'), { recursive: true });

const L = [];
const push = (s) => L.push(s);

push('; generated by OrcaSlicer 2.2.0 (test fixture)');
push('; total layer number: 10');
push('; layer_height = 0.2');
push(';TYPE:Custom');
push('G90 ; absolute positioning');
push('M83 ; relative extrusion');

let z = 0.0;
const layerHeights = [0.25, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2];

for (let i = 0; i < layerHeights.length; i++) {
  const h = layerHeights[i];
  push(';LAYER_CHANGE');
  push(`;Z:${z.toFixed(2)}`);
  push(`;HEIGHT:${h}`);
  push(';WIDTH:0.42');
  push('; printing object benchy.stl_id_0_copy_0');
  push(';TYPE:External perimeter');
  push('G1 X100.000 Y100.000 F12000');
  push(`G1 X110.000 Y100.000 E0.01000 F2400 ; outer`);
  push('G1 X110.000 Y110.000 E0.01000');
  push('G1 X100.000 Y110.000 E0.01000');
  push('G1 X100.000 Y100.000 E0.01000');

  // consecutive inner walls (Orca "Inner/Outer" order): all in one group
  const walls = [
    ['102.500', '102.500', '107.500', '107.500'],
    ['105.000', '105.000', '106.000', '106.000'],
  ];
  for (const [x0, y0, x1, y1] of walls) {
    push(';TYPE:Inner wall');
    push(`G1 X${x0} Y${y0} E0.00200`);
    push(`G1 X${x1} Y${y0} E0.00400`);
    push(`G1 X${x1} Y${y1} E0.00400`);
    push(`G1 X${x0} Y${y1} E0.00400`);
    push(`G1 X${x0} Y${y0} E0.00400`);
  }

  push(';WIPE_START');
  push('G1 X105.000 Y104.000 E-0.00400');
  push('G1 E-0.40000 F2100 ; retract');
  push(';WIPE_END');
  push('G1 X90.000 Y90.000 F12000 ; travel');
  push('G1 E0.40000 F2100 ; unretract');
  push(';TYPE:Sparse infill');
  push(`G1 X101.000 Y101.000 E0.00200 F2400`);
  push('G1 X109.000 Y101.000 E0.00800');
  push('G1 X109.000 Y109.000 E0.00800');
  push('G1 X101.000 Y109.000 E0.00800');
  push('G1 X101.000 Y101.000 E0.00800');
  push('; stop printing object benchy.stl_id_0_copy_0');
  z += h;
}

push(';TYPE:Custom');
push('G1 X105.000 Y110.000 E0.00000');
push('G1 X105.000 Y100.000 E0.00000');
push(';END of PRINT');

const text = L.join('\n') + '\n';
writeFileSync(join(here, 'golden/orca_fixture.gcode'), text);
console.log(`fixture: ${layerHeights.length} layers, ${L.length} lines, ${text.length} bytes`);
